In [1]:
"""
Simple TensorFlow exercises
You should thoroughly test your code
"""

import tensorflow as tf

###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))

In [2]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

# YOUR CODE
x = tf.random_uniform([], minval= -1, maxval= 1)
y = tf.random_uniform([], minval= -1, maxval= 1)
out = tf.case({tf.less(x, y): lambda: tf.add(x, y), 
            tf.greater(x, y): lambda: tf.subtract(x, y)}, 
            default=lambda: tf.constant(0.0), exclusive=True)
print(x)
sess = tf.InteractiveSession()
print(sess.run([x, y, out]))

Tensor("random_uniform_2:0", shape=(), dtype=float32)
[0.10830498, -0.38102031, 0.48932528]


 ```
    trandom_uniform(
    shape,
    minval=0,
    maxval=None,
    dtype=tf.float32,
    seed=None,
    name=None
)
```
* The generated values follow a uniform distribution in the range [minval, maxval). The lower bound minval is included in the range, while the upper bound maxval is excluded.
* For floats, the default range is [0, 1). For ints, at least maxval must be specified explicitly.


In [3]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

# YOUR CODE
x = tf.constant( [[0, -2, -1], [0, 1, 2]] )
y = tf.zeros_like(x)
out = tf.equal(x, y)

print(x)
sess = tf.InteractiveSession()
print(sess.run(x))
print(sess.run(y))
print(sess.run(out))

Tensor("Const:0", shape=(2, 3), dtype=int32)
[[ 0 -2 -1]
 [ 0  1  2]]
[[0 0 0]
 [0 0 0]]
[[ True False False]
 [ True False False]]


In [4]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

# YOUR CODE
x = tf.constant( [29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(tf.greater(x, 30))
out = tf.gather(x, indices)
out1 = tf.boolean_mask(x, tf.greater(x, 30))  ## using tf.boolean_mask

sess = tf.InteractiveSession()
print(sess.run(indices))
print(sess.run(out))
print(sess.run(out1))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]
[ 31.19073486  30.97266006  38.08450317  34.94445419  34.45999146
  36.01657104  30.20379066  33.71149445  36.05556488]


In [5]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

# YOUR CODE

#values = tf.range(1, 7)
out = tf.diag(list(range(1,7)))
out1 = tf.diag(tf.range(1,7))

sess = tf.InteractiveSession()
print(sess.run(out))
print()
print(sess.run(out1))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [6]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

# YOUR CODE
x = tf.random_normal([10,10], mean=0, stddev=1)
out = tf.matrix_determinant(x)


sess = tf.InteractiveSession()
print(sess.run(out))

10.6445


In [7]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

# YOUR CODE
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9], dtype=tf.int16)
out = tf.unique(x)
y = out[0]
idx = out[1]
shape_y = tf.shape(y)
size_y = tf.size(y)

sess = tf.InteractiveSession()
print(sess.run(out))
print(sess.run(y))
print(sess.run(idx))
print(sess.run(shape_y))
print(sess.run(size_y))

Unique(y=array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int16), idx=array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8]))
[ 5  2  3 10  6  4  1  0  9]
[0 1 2 0 3 4 1 2 5 1 6 6 7 8]
[9]
9


In [8]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

# YOUR CODE
x = tf.random_normal([300], mean=0, stddev=1)
y = tf.random_normal([300], mean=0, stddev=1)
mse = tf.reduce_mean(tf.square(tf.subtract(x, y)))
sav = tf.reduce_sum(tf.abs(tf.subtract(x, y)))
avg = tf.reduce_mean(tf.subtract(x,y))

out = tf.cond(tf.less(avg, 0), lambda: avg, lambda:  sav)

In [9]:
sess = tf.InteractiveSession()
print(sess.run([mse, sav, avg, out]))

[2.1149266, 354.47269, 0.03868562, 354.47269]
